import { AiScopeType } from '../../components';

export const sampleScopeOptions = [
  {
    id: '1',
    displayName: '1. Code',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/code.svg',
  },
  {
    id: '2',
    displayName: '2. AWS CLI',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/aws.png',
  },
  {
    id: '3',
    displayName: '3. Azure CLI',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/azure.svg',
  },
  {
    id: '4',
    displayName: '4. Slack Message',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/slack.png',
  },
  {
    id: '5',
    displayName: '5. Code',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/code.svg',
  },
  {
    id: '6',
    displayName: '6. AWS CLI',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/aws.png',
  },
  {
    id: '7',
    displayName: '7. Azure CLI',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/azure.svg',
  },
  {
    id: '8',
    displayName: '8. Slack Message',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/slack.png',
  },
  {
    id: '9',
    displayName: '9. Code',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/code.svg',
  },
  {
    id: '10',
    displayName: '10. AWS CLI',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/aws.png',
  },
  {
    id: '11',
    displayName: '11. Azure CLI',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/azure.svg',
  },
  {
    id: '12',
    displayName: '12. Slack Message',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/slack.png',
  },
  {
    id: '13',
    displayName: '13. Code',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/code.svg',
  },
  {
    id: '14',
    displayName: '14. AWS CLI',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/aws.png',
  },
  {
    id: '15',
    displayName: '15. Azure CLI',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/azure.svg',
  },
  {
    id: '16',
    displayName: '16. Slack Message',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/slack.png',
  },
  {
    id: '17',
    displayName: '17. Code',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/code.svg',
  },
  {
    id: '18',
    displayName: '18. AWS CLI',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/aws.png',
  },
  {
    id: '19',
    displayName: '19. Azure CLI',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/azure.svg',
  },
  {
    id: '20',
    displayName: '20. Slack Message',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/slack.png',
  },
  {
    id: '21',
    displayName: '21. Slack Message With Very Long Name',
    type: AiScopeType.STEP,
    logoUrl: 'https://static.openops.com/blocks/slack.png',
  },
];
